
export type OnboardingStep = {
  focus?: string,
  message?: string,
  positionClassName?: string,
};

export const haikuOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div>I built this for haiku enthusiasts to make and share their creations, and also to have a bit of fun with <b><a href="https://en.wikipedia.org/wiki/Large_language_model" target="_blank">Large Language Models</a></b>. Enjoy and share your creations!</div>
        <div>Follow the next steps to learn all about <b>Haiku Genius</b>.</div>
      </div>
    `,
    positionClassName: "top-[50vh] -translate-y-1/2 left-3",
  },
  {
    focus: "poem",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>This haiku poem was created with the assistance of ChatGPT, with art specifically generated by DALL-E to blend with the poem.</div>
        <div>AI-generated haiku poems are sometimes good, sometimes less good! Click on the haiku poem or the button next to it to copy the poem's text.</div>
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",

  },
  {
    focus: "logo-and-generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haikus will be featured every day. Click on the logo to return to today's, and come back tomorrow for a new one!</div>
        <div>To create your very own hit the generate button at the top of the screen and pick a theme: AI will help you write a poem and generate art work to match.</div>
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",

  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus (viewed or created) in the side panel to the left.</div>
        <div>To access the source code, learn more about me, or access a link to share this haiku see the buttons at the bottom.</div>
        <div>Enjoy <b>Haiku Genius!</b></div>        
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",
  },
];

export const haikudleOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div><b>Wordle</b>: a word game with a single daily solution, with all players attempting to guess the same word. Learn more <b><a href="https://en.wikipedia.org/wiki/Wordle" target="_blank">here</a></b>.</div>
        <div>Unscramble the poem to solve today's haiku puzzle and reveal the art work!</div>
        <div>Follow the next steps to learn all about <b>Haikudle</b>.</div>
      </div>`,
    positionClassName: "top-[50vh] -translate-y-1/2 left-3",
  },
  {
    focus: "puzzle",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>The poem's words have been moved around and the art blurred. Different styling indicates which word is in the correct place.</div>
        <div>Drag-and-drop or swap (tap/click on one then another) words to their correct places and the art work will be revealed.</div>
        <div>Daily puzzles only last for the day: solve and share before time runs out!</div>
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",

  },
  {
    focus: "logo-and-generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haiku puzzle will be featured every day. Click on the logo to return to today's, and come back to tomorrow for a new puzzle!</div>
        <div>To create your very own haikus hit the generate button at the top of the screen and pick a theme: AI will help you write a poem and generate art work to match.</div>
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",

  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus (solved or created) in the side panel to the left.</div>
        <div>To access the source code, learn more about me, or access a link to share this haiku see the buttons at the bottom of the screen.</div>
        <div>Enjoy <b>Haikudle!</b></div>        
      </div>
    `,
    positionClassName: "bottom-[10vh] left-3",
  },
];
