import { formatTimeFromNow } from "@/utils/format";
import { Haiku } from "./Haiku";

export type OnboardingStep = {
  focus?: string,
  message?: string,
  style?: any | undefined,
};

export const haikuOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div>I built this for haiku enthusiasts to make and share their creations, but also for me to have a bit of fun with <b><a href="https://en.wikipedia.org/wiki/Large_language_model" target="_blank">Large Language Models</a></b>.</div>
        <div>Hit the <b>Create</b> button at the top of screen to start crafting your own haiku and share it with the world!</div>
        <div>Follow the next steps to learn all about <b>Haiku Genius</b>.</div>
      </div>
    `,
    style: { bottom: "50%", transform: "translateY(50%)" },
  },
  {
    focus: "poem",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>This haiku poem was created with the assistance of <b>ChatGPT</b>, with the imagery generated by <b>DALL-E</b> to blend with the poem.</div>
        <div>AI-generated content is often good, but sometimes less so! Haiku creators start with a generated poem, then their creativity takes over.</div>
      </div>
    `,
    style: { bottom: "10%" },
  },
  {
    focus: "generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haiku will be featured every day, maybe one of yours! Click on the logo in the side panel to see today's, come back tomorrow for more.</div>
        <div>To create your own haiku hit the <b>Create</b> button at the top of the screen, maybe pick a theme and AI will get you started. The rest is up to!</div>
      </div>
    `,
    style: { bottom: "10%" },
  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus in the side panel to the left.</div>
        <div>To learn about me, access the source code, <b>like</b>, <b>copy</b> or <b>share</b> this haiku see the buttons at the bottom.</div>
        <div>For the best mobile experience hit the <b>Add to Home Screen</b> under the <b>Share</b> or <b>three-dot menu icon</b>.</div>
        <div>Enjoy <b>Haiku Genius!</b></div>        
      </div>
    `,
    style: { bottom: "10%" },
  },
];

export const haikuGeneratedOnboardingSteps = (haiku: Haiku) => [
  {
    focus: "poem-actions",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>
          This haiku was${haiku?.version ? " initially" : ""} generated on the theme <i>${haiku?.theme}</i>${haiku?.mood ? ` with a <i>${haiku?.mood}</i> mood using <b>ChatGPT</b>` : ""}. 
          Both theme and mood were used to generate the art using <b>DALL-E</b> with a curated prompt to harmonize with the poem, with specific instructions: <i>${haiku.artStyle}</i>.
        </div>
        <div>Try the buttons next to the poem to edit or regenerate the poem, or generate another image with the same theme and mood. Use your mouse, keyboard, arrow keys, Tab, Escape and Enter keys to <b>edit, cancel or save.</b></div>
        <div>Level up your creativity with AI! save with empty or incomplete lines, or use "..." placeholders for <b>AI to fill in.</b>
      </div>`,
    style: { top: "0.5rem" },
  },
];

export const haikuPromptSteps = (haiku: Haiku) => [
  {
    focus: "poem",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Theme and mood: <i>${haiku.theme}</i> and <i>${haiku.mood}</i></div>      
        <div>Image style: <i>${haiku.artStyle || "N/A"}</i></div>      
        <!-- <div>Poem prompt: <i>${haiku.poemPrompt || "N/A"}</i></div> -->
        <div>Image prompt: <i>${haiku.imagePrompt || "N/A"}</i></div>
        ${haiku.version || haiku.deprecated
          ? `<div>Version: ${haiku.version}
            ${haiku.version
            ? ` <a href="/${haiku.id}?version=${haiku.version - 1}">(Load previous)</a>`
            : ""}
            ${haiku.deprecated
            ? ` <a href="/${haiku.id}">(Load current)</a>`
            : ""}</div>`
          : ""}    
        <div>Created by: user ${haiku.createdBy} ${formatTimeFromNow(haiku.createdAt || 0)}</div>      
        ${haiku.updatedBy ? `<div>Updated by: user ${haiku.updatedBy} ${formatTimeFromNow(haiku.updatedAt || 0)}</div>` : ""} 
      </div>`,
    style: { bottom: "50%", transform: "translateY(50%)" },
  },
];

export const haikudleOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div><b>Wordle</b>: a word game with a single daily solution, with all players attempting to guess the same word. Learn more <b><a href="https://en.wikipedia.org/wiki/Wordle" target="_blank">here</a></b>.</div>
        <div>Unscramble the poem to solve today's haiku puzzle and reveal the art work!</div>
        <div>Follow the next steps to learn all about <b>Haikudle</b>.</div>
      </div>`,
    style: { bottom: "50%", transform: "translateY(50%)" },
  },
  {
    focus: "puzzle",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>The poem's words have been moved around and the art blurred. Different styling indicates which word is in the correct place.</div>
        <div>Drag-and-drop or swap (tap/click on one then another) words to their correct places and the art work will be revealed.</div>
        <div>Daily puzzles only last for the day: solve and share before time runs out!</div>
      </div>
    `,
    style: { bottom: "10%" },
  },
  {
    focus: "logo-and-generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haiku puzzle will be featured every day. Click on the logo in the side panel to return to today's, and come back to tomorrow for a new puzzle!</div>
        <div>To create your very own haikus hit the <b>Create</b> button at the top of the screen and pick a theme or subject: AI will get you started writing a poem and will generate art work to match.</div>
      </div>
    `,
    style: { bottom: "10%" },
  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus (solved or created) in the side panel to the left.</div>
        <div>To access the source code, learn more about me, or access a link to share this haiku see the buttons at the bottom of the screen.</div>
        <div>Enjoy <b>Haikudle!</b></div>        
      </div>
    `,
    style: { bottom: "10%" },
  },
];
