import { Haiku } from "./Haiku";

export type OnboardingStep = {
  focus?: string,
  message?: string,
  style?: any | undefined,
};

export const haikuOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div>I built this for haiku enthusiasts to make and share their creations, but also for me to have a bit of fun with <b><a href="https://en.wikipedia.org/wiki/Large_language_model" target="_blank">Large Language Models</a></b>. Enjoy and share with the world!</div>
        <div>Follow the next steps to learn all about <b>Haiku Genius</b>.</div>
      </div>
    `,
    style: { bottom: "50vh", transform: "translateY(50%)" },
  },
  {
    focus: "poem",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>This haiku poem was created with the assistance of <b>ChatGPT</b>, with the imagery generated by <b>DALL-E</b> to blend with the poem.</div>
        <div>AI-generated content is often good, but sometimes less so! Haiku creators start with a generated poem, then their creativity takes over.</div>
      </div>
    `,
    style: { bottom: "10vh" },
  },
  {
    focus: "logo-and-generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haiku will be featured every day, maybe one of yours! Click on the logo to see today's, come back tomorrow for more.</div>
        <div>To create your own haiku hit the <b>generate</b> button at the top of the screen and pick a theme: we'll get you started and the rest is up to!</div>
      </div>
    `,
    style: { bottom: "10vh" },
  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus in the side panel to the left.</div>
        <div>To learn about me, access the source code, copy or share this haiku see the buttons at the bottom.</div>
        <div>For the best mobile experience hit the 'Add to Home Screen' under the Share or three-dot menu icon.</div>
        <div>Enjoy <b>Haiku Genius!</b></div>        
      </div>
    `,
    style: { bottom: "10vh" },
  },
];

export const haikuGeneratedOnboardingSteps = (haiku: Haiku) => [
  {
    focus: "poem-actions",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>This haiku was generated on the theme <i>${haiku?.theme}</i>${haiku?.mood ? ` with a <i>${haiku?.mood}</i> mood using <b>ChatGPT</b>` : ""}. Both were used to generate art using <b>DALL-E</b> with a curated prompt to harmonize together.</div>
        <div>Curious about those prompts? See <b><a href="https://github.com/desmat/haiku/blob/main/services/openai.ts#L106-L108" target="_blank">here</a></b> and <b><a href="https://github.com/desmat/haiku/blob/main/services/openai.ts#L17-L31" target="_blank">here</a></b> in the source code.</b></div>
        <div>Try the buttons next to the poem to edit or regenerate. Use your mouse, keyboard, arrow keys, Tab, Escape and Enter keys to edit, cancel or save.</div>
        <div>Level up your creativity with our AI assistant: save with empty or incomplete lines, or "..." as placeholders for to fill in.
      </div>`,
    style: { bottom: "50vh" },
  },
];

export const haikudleOnboardingSteps = [
  {
    focus: "",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div><b>Haiku</b>: a Japanese poetic form that consists of three lines, with 5/7/5 syllable per line, traditionally evoking images of the natural world. Learn more <b><a href="https://en.wikipedia.org/wiki/Haiku" target="_blank">here</a></b>.</div>
        <div><b>Wordle</b>: a word game with a single daily solution, with all players attempting to guess the same word. Learn more <b><a href="https://en.wikipedia.org/wiki/Wordle" target="_blank">here</a></b>.</div>
        <div>Unscramble the poem to solve today's haiku puzzle and reveal the art work!</div>
        <div>Follow the next steps to learn all about <b>Haikudle</b>.</div>
      </div>`,
    style: { bottom: "50vh", transform: "translateY(50%)" },
  },
  {
    focus: "puzzle",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>The poem's words have been moved around and the art blurred. Different styling indicates which word is in the correct place.</div>
        <div>Drag-and-drop or swap (tap/click on one then another) words to their correct places and the art work will be revealed.</div>
        <div>Daily puzzles only last for the day: solve and share before time runs out!</div>
      </div>
    `,
    style: { bottom: "10vh" },
  },
  {
    focus: "logo-and-generate",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>A new haiku puzzle will be featured every day. Click on the logo to return to today's, and come back to tomorrow for a new puzzle!</div>
        <div>To create your very own haikus hit the generate button at the top of the screen and pick a theme: AI will help you write a poem and generate art work to match.</div>
      </div>
    `,
    style: { bottom: "10vh" },
  },
  {
    focus: "side-panel-and-bottom-links",
    message: `
      <div style="display: flex; flex-direction: column; gap: 0.4rem;">
        <div>Find all your haikus (solved or created) in the side panel to the left.</div>
        <div>To access the source code, learn more about me, or access a link to share this haiku see the buttons at the bottom of the screen.</div>
        <div>Enjoy <b>Haikudle!</b></div>        
      </div>
    `,
    style: { bottom: "10vh" },
  },
];
